import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 Tauri App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center bg-black">
        <div className="flex flex-col items-center gap-2">
          <p className="text-2xl font-semibold text-white">Hello</p>
        </div>
      </main>
    </>
  );
};

export default Home;
